---

- name: "Install mariadb-server packages"
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - mariadb-server
    - python-mysqldb

- name: "Install extra packages"
  apt:
    name: "{{ item }}"
    state: present
  with_items: "{{ mariadb__extra_packages }}"

- name: "Remove old log files"
  file: "path={{ item }} state=absent"
  with_items:
    - /var/log/mysql.err
    - /var/log/mysql.log
