---
# tasks file for mariadb

- include: install_debian.yml
  when: ansible_os_family == 'Debian'

# Add RedHat when needed
#- include: install_redhat.yml
#  when: ansible_os_family == 'RedHat'

# Needed in some case where the daemon is not automatically
# startup at installation
- name: "Force service start"
  service: name=mysql state=started

- include: secure_installation.yml

- include: change_characterset.yml
